model:
  resolution: 160
  n_channels: 6
  channels: [32, 64, 128, 256, 512]
  asr_mode: "ave"

train:
  epochs: 100
  batch_size: 8
  lr: 0.001
  num_workers: 8
  use_syncnet: true
  use_amp: true

inference:
  batch_size: 4
  device: "auto"
  output_codec: "libx264"
  output_crf: 10
  fps: 25
